export const FIND_ALL_CARS = "FIND_ALL_CARS";
export const FIND_ALL_ROBOTS = "FIND_ALL_ROBOTS";
export const FIND_ALL_STATIONS = "FIND_ALL_STATIONS";
export const FIND_ALL_EMPLOYEES = "FIND_ALL_EMPLOYEES";
export const FIND_ALL_PRODUCTION_LINES = "FIND_ALL_PRODUCTION_LINES";
export const SAVE_CAR = "SAVE_CAR"
export const SAVE_ROBOT = "SAVE_ROBOT"
export const SAVE_STATION = "SAVE_STATION"
export const SAVE_EMPLOYEE = "SAVE_EMPLOYEE"
export const SAVE_PRODUCTION_LINE = "SAVE_PRODUCTION_LINE"
export const UPDATE_STATION = "UPDATE_STATION"
export const START_PRODUCTION_LINE = "START_PRODUCTION_LINE";
export const STOP_PRODUCTION_LINE = "STOP_PRODUCTION_LINE";


export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";